export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const CREATE_RECIPE = 'CREATE_RECIPE';
export const ADD_METHOD = 'ADD_METHOD';
export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const CLEAR_RECIPE = 'CLEAR_RECIPE';
export const SET_USER_RECIPES = 'SET_USER_RECIPES';
export const SET_CURRENT_RECIPE = 'SET_CURRENT_RECIPE';